version: '3.8'

services:
  agente-impressao:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agente-impressao
    network_mode: host
    restart: unless-stopped
    environment:
      - NODE_ENV=production
