version: '3.8'

services:
  agente-impressao:
    build:
      context: https://github.com/francauto/agente-de-impressao.git
      dockerfile: Dockerfile
    container_name: agente-impressao
    network_mode: host
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-4005}
